
  create table "public"."new_test_table" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now()
      );


alter table "public"."new_test_table" enable row level security;

CREATE UNIQUE INDEX new_test_table_pkey ON public.new_test_table USING btree (id);

alter table "public"."new_test_table" add constraint "new_test_table_pkey" PRIMARY KEY using index "new_test_table_pkey";

grant delete on table "public"."new_test_table" to "anon";

grant insert on table "public"."new_test_table" to "anon";

grant references on table "public"."new_test_table" to "anon";

grant select on table "public"."new_test_table" to "anon";

grant trigger on table "public"."new_test_table" to "anon";

grant truncate on table "public"."new_test_table" to "anon";

grant update on table "public"."new_test_table" to "anon";

grant delete on table "public"."new_test_table" to "authenticated";

grant insert on table "public"."new_test_table" to "authenticated";

grant references on table "public"."new_test_table" to "authenticated";

grant select on table "public"."new_test_table" to "authenticated";

grant trigger on table "public"."new_test_table" to "authenticated";

grant truncate on table "public"."new_test_table" to "authenticated";

grant update on table "public"."new_test_table" to "authenticated";

grant delete on table "public"."new_test_table" to "postgres";

grant insert on table "public"."new_test_table" to "postgres";

grant references on table "public"."new_test_table" to "postgres";

grant select on table "public"."new_test_table" to "postgres";

grant trigger on table "public"."new_test_table" to "postgres";

grant truncate on table "public"."new_test_table" to "postgres";

grant update on table "public"."new_test_table" to "postgres";

grant delete on table "public"."new_test_table" to "service_role";

grant insert on table "public"."new_test_table" to "service_role";

grant references on table "public"."new_test_table" to "service_role";

grant select on table "public"."new_test_table" to "service_role";

grant trigger on table "public"."new_test_table" to "service_role";

grant truncate on table "public"."new_test_table" to "service_role";

grant update on table "public"."new_test_table" to "service_role";


